<?php
session_start();
require_once 'config.php';
require_once 'lib/fpdf.php';

if (!isset($_SESSION['farm_data'])) {
    header('Location: index.php');
    exit;
}

require_once 'db.php';
$data = $_SESSION['farm_data'];

// ── System Settings ─────────────────────────────────────────
$stmt = $pdo->query("SELECT * FROM settings");
$sys_settings = [];
foreach ($stmt->fetchAll() as $s) {
    $sys_settings[$s['setting_key']] = $s['setting_value'];
}
$site_name = $sys_settings['site_name'] ?? 'InfoCrop AI';

// ── PDF Class ───────────────────────────────────────────────
class FarmPDF extends FPDF {
    protected $site_name;
    protected $contact_info;

    function setInfo($site_name, $contact_info) {
        $this->site_name   = $site_name;
        $this->contact_info = $contact_info;
    }

    function Header() {
        if ($this->PageNo() === 1) {
            // Full header on first page only
            $this->SetFont('Arial', 'B', 15);
            $this->SetTextColor(27, 94, 32);
            $this->Cell(0, 10, clean_pdf_text($this->site_name . ' Farm Plan Report'), 0, 1, 'C');
            $this->SetFont('Arial', 'I', 10);
            $this->SetTextColor(85, 85, 85);
            $this->Cell(0, 10, 'Complete Pre-Crop Information Report', 0, 1, 'C');
            $this->Ln(5);
            $this->Line(10, $this->GetY(), 200, $this->GetY());
            $this->Ln(10);
        } else {
            // Continuation pages: just a thin separator line at top
            $this->SetDrawColor(200, 220, 200);
            $this->SetLineWidth(0.3);
            $this->Line(10, 12, 200, 12);
            $this->SetY(18); // leave a small top margin
        }
    }

    function Footer() {
        $this->SetY(-20);
        $this->SetFont('Arial', 'I', 8);
        $this->SetTextColor(128, 128, 128);
        $phone = $this->contact_info['contact_phone'] ?? '+91 8010094034';
        $email = $this->contact_info['contact_email'] ?? 'jagadledayanand2550@gmail.com';
        $contact = "Phone: " . $phone . " | Email: " . $email;
        if (!empty($this->contact_info['contact_website'])) {
            $contact .= " | Web: " . $this->contact_info['contact_website'];
        } else {
            $contact .= " | Web: infocropai.free.nf";
        }
        $this->Cell(0, 5, clean_pdf_text($contact), 0, 1, 'C');
        $this->Cell(0, 5, clean_pdf_text('Page ' . $this->PageNo() . '/{nb} - Generated by ' . $this->site_name), 0, 0, 'C');
    }

    // NbLines helper for MultiCell height calculation
    function NbLines($w, $txt) {
        $cw = &$this->CurrentFont['cw'];
        if($w==0) $w = $this->w - $this->rMargin - $this->x;
        $wmax = max(1, ($w-2*$this->cMargin)*1000/$this->FontSize);
        $s = str_replace("\r", '', $txt);
        $nb = strlen($s);
        if($nb>0 && $s[$nb-1]=="\n") $nb--;
        $sep = -1; $i = 0; $j = 0; $l = 0; $nl = 1;
        while($i<$nb) {
            $c = $s[$i];
            if($c=="\n") { $i++; $sep = -1; $j = $i; $l = 0; $nl++; continue; }
            if($c==' ') $sep = $i;
            $l += (isset($cw[$c]) ? $cw[$c] : 0);
            if($l>$wmax) {
                if($sep==-1) { if($i==$j) $i++; }
                else $i = $sep+1;
                $sep = -1; $j = $i; $l = 0; $nl++;
            } else $i++;
        }
        return $nl;
    }
}

$pdf = new FarmPDF();
$pdf->setInfo($site_name, $sys_settings);
$pdf->AliasNbPages();
$pdf->SetAutoPageBreak(true, 25); // 25mm bottom margin clears the 20mm footer
$pdf->AddPage();

// Summary Box
$pdf->SetFillColor(232, 245, 233);
$pdf->Rect(10, $pdf->GetY(), 190, 40, 'F');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 10, 'Farmer Name:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(60, 10, clean_pdf_text($data['farmer_name'] ?? 'N/A'), 0, 0);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 10, 'Date:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(50, 10, date('d M Y'), 0, 1);

$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 10, 'Location:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(60, 10, clean_pdf_text(($data['city'] ?? 'N/A') . ', ' . ($data['state'] ?? 'N/A')), 0, 0);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 10, 'Season:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(50, 10, clean_pdf_text($data['season'] ?? 'N/A'), 0, 1);

$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 10, 'Crop:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(60, 10, clean_pdf_text($data['confirmed_crop'] ?? $data['crop_recommendation_TOP_CROP'] ?? 'N/A'), 0, 0);
$pdf->SetFont('Arial', 'B', 10);
$pdf->Cell(40, 10, 'Land Area:', 0, 0);
$pdf->SetFont('Arial', '', 10);
$pdf->Cell(50, 10, ($data['land_area'] ?? 'N/A') . ' Acres', 0, 1);

$pdf->Ln(15);

// Stages
foreach ($stages as $s) {
    if ($pdf->GetY() > 240) {
        $pdf->AddPage();
    }
    
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(27, 94, 32);
    $pdf->Cell(0, 10, clean_pdf_text('Stage ' . $s['num'] . ': ' . $s['title']), 0, 1);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(5);
    
    // Inputs Table
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetFillColor(27, 94, 32);
    $pdf->SetFont('Arial', 'B', 9);
    $pdf->Cell(60, 8, 'Field', 1, 0, 'C', true);
    $pdf->Cell(130, 8, 'Your Input', 1, 1, 'C', true);
    
    $pdf->SetTextColor(51, 51, 51);
    $pdf->SetFont('Arial', '', 9);
    foreach ($s['fields'] as $field) {
        $val = $data[$field['name']] ?? '';
        if ($val !== '' && $val !== 'Select') {
            $pdf->Cell(60, 7, clean_pdf_text($field['label']), 1);
            $pdf->Cell(130, 7, clean_pdf_text($val), 1, 1);
        }
    }
    $pdf->Ln(5);
    
    // AI Guidance
    $gkey = 'gemini_' . $s['gemini_key'];
    if (isset($data[$gkey])) {
        $pdf->SetFont('Arial', 'B', 11);
        $pdf->SetTextColor(2, 119, 189);
        $pdf->Cell(0, 10, 'AI Guidance (InfoCrop):', 0, 1);
        $pdf->SetTextColor(51, 51, 51);
        
        $lines      = explode("\n", $data[$gkey]);
        $in_table   = false;
        $table_data = [];

        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '') {
                if ($in_table) { renderPDFTable($pdf, $table_data); $in_table = false; $table_data = []; }
                $pdf->Ln(2); continue;
            }

            if (preg_match('/^(#{1,4})\s+(.+)$/', $line, $m)) {
                if ($in_table) { renderPDFTable($pdf, $table_data); $in_table = false; $table_data = []; }
                $pdf->SetFont('Arial', 'B', 10);
                $pdf->SetTextColor(27, 94, 32);
                $pdf->Cell(0, 8, clean_pdf_text($m[2]), 0, 1);
                $pdf->SetFont('Arial', '', 9);
                $pdf->SetTextColor(51, 51, 51);
                continue;
            }

            if (strpos($line, '|') !== false && substr_count($line, '|') > 1) {
                if (preg_match('/^[|:\- ]+$/', $line)) continue;
                $in_table = true;
                $table_data[] = array_map('trim', explode('|', trim($line, '|')));
                continue;
            } else {
                if ($in_table) { renderPDFTable($pdf, $table_data); $in_table = false; $table_data = []; }
            }

            if (preg_match('/^([-*•]|\d+\.)\s+(.+)$/u', $line, $m)) {
                $bullet = ($m[1] == '-' || $m[1] == '*' || $m[1] == '•') ? chr(149) : $m[1];
                $pdf->SetFont('Arial', 'B', 9);
                $pdf->Cell(8, 6, clean_pdf_text($bullet), 0, 0, 'R');
                $pdf->SetFont('Arial', '', 9);
                $pdf->MultiCell(0, 6, clean_pdf_text(str_replace('**', '', $m[2])));
                continue;
            }

            $pdf->SetFont('Arial', '', 9);
            $pdf->MultiCell(0, 5, clean_pdf_text(str_replace('**', '', $line)));
            $pdf->Ln(1);
        }
        if ($in_table) { renderPDFTable($pdf, $table_data); }
    }
    $pdf->Ln(10);
}

// Helper: clean text for PDF
function clean_pdf_text($text) {
    if (!is_string($text)) $text = (string)($text ?? '');
    if ($text === '') return '';

    // Preserve meaningful symbols before stripping
    $text = str_replace(['₹', 'â‚¹'], 'Rs.', $text);
    $text = str_replace(['★', '☆', '⭐'], '*', $text);
    $text = str_replace(['✔', '✓'], '[OK]', $text);
    $text = str_replace(['✖', '✗', '✘'], '[X]', $text);
    $text = str_replace(['→', '➔', '➜', '➡'], '->', $text);
    $text = str_replace(['←'], '<-', $text);
    $text = str_replace(['↑'], '^', $text);
    $text = str_replace(['↓'], 'v', $text);
    $text = str_replace(['•', '●', '◉'], chr(149), $text);
    $text = str_replace(['—', '–'], '-', $text);
    $text = str_replace(["\u{2018}", "\u{2019}", "\u{201A}"], "'", $text);
    $text = str_replace(["\u{201C}", "\u{201D}", "\u{201E}"], '"', $text);
    $text = str_replace("\u{2026}", '...', $text);

    // Strip ALL emoji & symbol Unicode blocks comprehensively
    $text = (string) preg_replace('/[\x{1F000}-\x{1FFFF}]/u', '', $text);  // All SMP emojis
    $text = (string) preg_replace('/[\x{2600}-\x{27BF}]/u', '', $text);    // Misc symbols, Dingbats
    $text = (string) preg_replace('/[\x{FE00}-\x{FE0F}]/u', '', $text);    // Variation selectors
    $text = (string) preg_replace('/[\x{200D}]/u', '', $text);             // Zero-width joiner
    $text = (string) preg_replace('/[\x{20E3}]/u', '', $text);             // Combining enclosing keycap
    $text = (string) preg_replace('/[\x{E0020}-\x{E007F}]/u', '', $text);  // Tags block
    $text = (string) preg_replace('/[\x{2300}-\x{23FF}]/u', '', $text);    // Misc technical
    $text = (string) preg_replace('/[\x{2B00}-\x{2BFF}]/u', '', $text);    // Misc symbols & arrows
    $text = (string) preg_replace('/[\x{3000}-\x{303F}]/u', '', $text);    // CJK symbols
    $text = (string) preg_replace('/[\x{25A0}-\x{25FF}]/u', '', $text);    // Geometric shapes
    $text = (string) preg_replace('/[\x{2190}-\x{21FF}]/u', '', $text);    // Arrows

    // Convert to Latin-1 (FPDF encoding)
    if (function_exists('iconv')) {
        $text = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $text) ?: $text;
    } else {
        $text = utf8_decode($text);
    }

    // Final safety: strip any remaining non-printable/non-Latin-1 characters
    $text = preg_replace('/[^\x20-\x7E\xA0-\xFF\n\r\t]/', '', $text);

    return trim($text);
}

// Helper: render table in PDF (premium layout)
function renderPDFTable($pdf, $data) {
    if (empty($data)) return;

    // Disable FPDF's auto page break – we manage breaks ourselves.
    // Without this, MultiCell fires its OWN AddPage() mid-row, producing blank pages.
    $pdf->SetAutoPageBreak(false);

    // ── Filter out pure separator / empty rows ──────────────────
    $filtered = [];
    $maxCols = 0;
    foreach ($data as $row) {
        $joined = implode('', array_map('trim', $row));
        if ($joined === '' || preg_match('/^[-:|\\s]+$/', $joined)) continue;
        $cleanedRow = array_map('trim', $row);
        $maxCols = max($maxCols, count($cleanedRow));
        $filtered[] = $cleanedRow;
    }
    if (empty($filtered)) { $pdf->SetAutoPageBreak(true, 10); return; }

    // Equalize columns (pad with empty string)
    foreach ($filtered as &$row) {
        while (count($row) < $maxCols) {
            $row[] = '';
        }
    }
    unset($row);

    $cols   = $maxCols;
    $total  = 190; // usable page width in mm

    // ── Smart column widths ─────────────────────────────────────
    if ($cols >= 3) {
        $firstW = $total * 0.20;
        $restW  = ($total - $firstW) / ($cols - 1);
        $widths = array_merge([$firstW], array_fill(0, $cols - 1, $restW));
    } else {
        $w = $total / $cols;
        $widths = array_fill(0, $cols, $w);
    }

    // ── Colours ─────────────────────────────────────────────────
    $hdrBg   = [27,  94,  32];
    $hdrFg   = [255, 255, 255];
    $rowEven = [245, 250, 245];
    $rowOdd  = [255, 255, 255];
    $rowFg   = [40,  40,  40];
    $borderR = 200; $borderG = 220; $borderB = 200;
    $boldBg  = [232, 245, 233];

    $lineH = 5;
    $padX  = 1.5;

    // ── Helpers ─────────────────────────────────────────────────
    $stripBold = fn($t) => trim(preg_replace('/\*{1,2}(.*?)\*{1,2}/u', '$1', $t));
    $rowIsBold = function($row) {
        foreach ($row as $cell) {
            if (preg_match('/\*\*.*?\*\*/', $cell)) return true;
        }
        return false;
    };

    // ── Inline helper: draw a single header row at current Y ────
    $drawHeader = function() use ($pdf, $filtered, $widths, $hdrBg, $hdrFg, $borderR, $borderG, $borderB, $stripBold) {
        $pdf->SetFont('Arial', 'B', 8.5);
        $pdf->SetTextColor(...$hdrFg);
        $pdf->SetFillColor(...$hdrBg);
        $pdf->SetDrawColor($borderR, $borderG, $borderB);
        $pdf->SetLineWidth(0.3);
        $x0 = $pdf->GetX(); $y0 = $pdf->GetY();
        foreach ($filtered[0] as $j => $cell) {
            $pdf->SetXY($x0 + array_sum(array_slice($widths, 0, $j)), $y0);
            $pdf->Cell($widths[$j], 9, clean_pdf_text($stripBold($cell)), 1, 0, 'C', true);
        }
        $pdf->Ln(9);
    };

    // Draw the first header
    $drawHeader();

    // ── Data rows ────────────────────────────────────────────────
    $pdf->SetFont('Arial', '', 8);
    $pdf->SetLineWidth(0.2);

    for ($i = 1; $i < count($filtered); $i++) {
        $row    = $filtered[$i];
        $isBold = $rowIsBold($row);

        // Calculate row height
        $maxLines = 1;
        foreach ($row as $j => $cell) {
            $txt      = clean_pdf_text($stripBold($cell));
            if (method_exists($pdf, 'NbLines')) {
                $lines = $pdf->NbLines(max(1, $widths[$j] - $padX * 2), $txt);
            } else {
                $cpl      = max(1, (int)(($widths[$j] - $padX * 2) / 2.0));
                $lines    = max(1, (int)ceil(strlen($txt) / $cpl));
            }
            $maxLines = max($maxLines, $lines);
        }
        $rowH = max(7, $maxLines * $lineH + 2);

        // Manual page break
        if ($pdf->GetY() + $rowH > 252) {  // 252 = 277mm page bottom minus 25mm footer margin
            $pdf->AddPage();
            $drawHeader();
            $pdf->SetFont('Arial', '', 8);
            $pdf->SetLineWidth(0.2);
        }

        // Row background & font
        if ($isBold) {
            $pdf->SetFillColor(...$boldBg);
            $pdf->SetFont('Arial', 'B', 8);
        } elseif ($i % 2 === 0) {
            $pdf->SetFillColor(...$rowEven);
        } else {
            $pdf->SetFillColor(...$rowOdd);
        }
        $pdf->SetTextColor(...$rowFg);   // ← always reset to dark BEFORE drawing
        $pdf->SetDrawColor($borderR, $borderG, $borderB);

        $x = $pdf->GetX();
        $y = $pdf->GetY();

        foreach ($row as $j => $cell) {
            $txt = clean_pdf_text($stripBold($cell));
            $cx  = $x + array_sum(array_slice($widths, 0, $j));
            $pdf->Rect($cx, $y, $widths[$j], $rowH, 'FD');
            $pdf->SetXY($cx + $padX, $y + 1);
            $pdf->MultiCell($widths[$j] - $padX * 2, $lineH, $txt, 0, 'L');
        }
        $pdf->SetXY($x, $y + $rowH);

        if ($isBold) $pdf->SetFont('Arial', '', 8);
    }

    // Bottom border
    $pdf->SetDrawColor($borderR, $borderG, $borderB);
    $pdf->SetLineWidth(0.3);
    $pdf->Line($pdf->GetX(), $pdf->GetY(), $pdf->GetX() + $total, $pdf->GetY());
    $pdf->Ln(4);

    // Restore auto page break for the rest of the document (25mm clears 20mm footer)
    $pdf->SetAutoPageBreak(true, 25);
}


// Final Disclaimer
if ($pdf->GetY() > 220) $pdf->AddPage();
$pdf->Ln(5);
$pdf->SetFont('Arial', 'B', 11);
$pdf->SetTextColor(27, 94, 32);
$pdf->Cell(0, 10, clean_pdf_text('Important Notes & Contact Support'), 0, 1);
$pdf->SetFont('Arial', '', 9);
$pdf->SetTextColor(51, 51, 51);

$disclaimer = "This farm plan was generated using AI analysis based on your inputs. Always cross-verify with certified agronomists.\n\n" .
              "For support, contact: " . ($sys_settings['contact_name'] ?? $site_name) . "\n" .
              "Phone: "   . ($sys_settings['contact_phone']   ?? '+91 8010094034') . "\n" .
              "Email: "   . ($sys_settings['contact_email']   ?? 'jagadledayanand2550@gmail.com') . "\n" .
              "Website: " . ($sys_settings['contact_website'] ?? 'infocropai.free.nf') . "\n\n" .
              "Generated by " . $site_name . " — Empowering Indian Farmers with AI";

$pdf->MultiCell(0, 5, clean_pdf_text($disclaimer));

// ── Build filename ───────────────────────────────────────────
$farmer_slug = preg_replace('/[^a-zA-Z0-9_]/', '', str_replace(' ', '_', $data['farmer_name'] ?? 'Farm'));
$ts          = date('Ymd_His');
$filename    = $site_name . '_FarmPlan_' . $farmer_slug . '_' . $ts . '.pdf';
$safe_filename = clean_pdf_text($filename);

// ── Save PDF to disk ─────────────────────────────────────────
$save_dir = __DIR__ . '/uploads/reports/';
if (!is_dir($save_dir)) {
    @mkdir($save_dir, 0755, true);
}
$save_path = $save_dir . $safe_filename;
$pdf->Output('F', $save_path); // 'F' = save to file

// ── Save record to database ──────────────────────────────────
$user_id = $_SESSION['user_id'] ?? null;
if ($user_id && file_exists($save_path)) {
    $crop_val     = $data['confirmed_crop']
                  ?? $data['crop_recommendation_TOP_CROP']
                  ?? ($data['crop'] ?? 'N/A');
    $location_val = trim(($data['city'] ?? '') . ', ' . ($data['state'] ?? ''), ', ');
    $report_json  = json_encode($data, JSON_UNESCAPED_UNICODE);

    $ins = $pdo->prepare("
        INSERT INTO farm_reports
            (user_id, farmer_name, crop, location, season, land_area, pdf_filename, report_data)
        VALUES
            (?, ?, ?, ?, ?, ?, ?, ?)
    ");
    $ins->execute([
        $user_id,
        $data['farmer_name']  ?? 'N/A',
        $crop_val,
        $location_val,
        $data['season']       ?? 'N/A',
        $data['land_area']    ?? 'N/A',
        $safe_filename,
        $report_json,
    ]);
}

// ── Stream PDF to browser ────────────────────────────────────
// Re-output from file so browser gets the download prompt
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="' . $safe_filename . '"');
header('Content-Length: ' . filesize($save_path));
readfile($save_path);
exit;
?>
